📊 AI Financial Market Data Analysis
🔹 Project Overview

This project analyzes financial and stock data of AI-focused companies using Python.
The goal is to understand how R&D spending, revenue growth, and events impact company performance and stock prices.

By working on this, I practiced:

Data cleaning and preprocessing

Exploratory Data Analysis (EDA)

Time-series and event impact analysis

Correlation studies and financial insights visualization

🔹 Key Insights Extracted

R&D Spending → How much each company spent on Research & Development.

Revenue Earned → Yearly AI revenue generated by the companies.

Date-wise Stock Impact → Stock performance trends over time.

Event-driven Stock Impact → Specific events that caused maximum stock fluctuations.

AI Revenue Growth → Long-term trend of AI-related revenue expansion.

Correlation Analysis → Relationship between R&D, revenue, and stock performance.

Expenditure vs Revenue (year-by-year) → Efficiency of R&D investment in generating revenue.

Event Impact Analysis → Measuring how major events shaped stock movements.

🔹 Tools & Libraries

Python (Jupyter Notebook)

Pandas → Data manipulation

Matplotlib & Seaborn → Visualization

Numpy → Numerical operations

🔹 Business Relevance

Helps companies evaluate if R&D investments are paying off.

Provides investors with insights on how events influence stock performance.

Useful for financial planning, trend analysis, and risk management.

Can be applied to real-world financial datasets for strategic decision-making.

🔹 Interview Prep Pointers

Why this project? → To connect AI innovation (R&D) with financial outcomes, while practicing Python-based data analysis.

Skills shown? → Data analysis, visualization, time-series analysis, correlation, and storytelling with data.

Real-world application? → Could be applied to real financial markets to support investment strategies, corporate planning, and event impact forecasting.
